coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 50%
        threshold: 1%
comment:
  layout: "reach, diff, flags, files"
  behavior: default
github_checks:
  annotations: true
